version: 2.1

jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
    - image: circleci/ruby:2.4.2-jessie-node # the primary container, where your job's commands are run
    - image: automationwizards/allure:1.4.24.RC3
      command: |
         docker run \
             -v $(pwd)/allure-report:/allure-report \   # Mandatory - Where to place the complied report
             -v $(pwd)/rspec:/allure-results \ # Mandatory - Where to look for test runs
             -v $(pwd)/allure-config:/allure-config \   # Optional - Where to look for an allure.properties file
             automationwizards/allure:1.4.24.RC3 allure report generate /allure-results -o /allure-report
    steps:
    - checkout # check out the code in the project directory
    - setup_remote_docker
    - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
    - run: mkdir ~/rspec
    - run:
        command: touch ~/rspec/rspec.xml
    - run:
        command: bundle exec rspec --format documentation  --format RspecJunitFormatter -o ~/rspec/rspec.xml
        when: always
    - store_artifacts:
        path: ~/rspec
        destination: build
    - store_test_results:
        path: ~/rspec