version: 2.1

jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
    - image: circleci/ruby:2.4.3-browsers # the primary container, where your job's commands are run
    steps:
    - checkout # check out the code in the project directory
#    - run:
#        command: sudo apt-get update && sudo apt-get install default-jre
    - run: sudo su -c 'echo "deb http://deb.debian.org/debian jessie-backports main" >> /etc/apt/sources.list'
    - run: |
        sudo rm -rf /var/lib/apt/lists/*
        sudo apt-get update
        sudo apt install -t jessie-backports  openjdk-8-jre-headless ca-certificates-java
    - run: sudo curl -o allure-2.6.0.tgz -Ls https://dl.bintray.com/qameta/generic/io/qameta/allure/allure/2.6.0/allure-2.6.0.tgz && sudo tar -zxvf allure-2.6.0.tgz -C /opt/ && ln -s /opt/allure-2.6.0/bin/allure /usr/bin/allure && allure --version
    - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
    - run: mkdir ~/rspec
    - run:
        command: touch ~/rspec/rspec.xml
    - run:
        command: bundle exec rspec --format documentation  --format RspecJunitFormatter -o ~/rspec/rspec.xml
        when: always
    - run:
        command: allure generate ~/rspec --report-dir ~/rspec/allure-reports
    - run:
        command: zip -r ~/rspec/allure.zip ~/rspec/allure-reports
#    - run:
#        command: rm -r ~/rspec/allure-reports
    - store_artifacts:
        path: ~/rspec
        destination: build
    - store_test_results:
        path: ~/rspec
