version: 2.1

jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
    - image: circleci/ruby:2.4.2-jessie-node # the primary container, where your job's commands are run
    steps:
    - checkout # check out the code in the project directory
    - run:
        command: sudo apt-get update && sudo apt install openjdk-8-jdk
    - run:
        command:  sudo npm install -g allure-commandline --save-dev
    - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
    - run: mkdir ~/rspec
    - run:
        command: touch ~/rspec/rspec.xml
    - run:
        command: bundle exec rspec --format documentation  --format RspecJunitFormatter -o ~/rspec/rspec.xml
        when: always
    - run:
        command: allure ~/rspec
    - store_artifacts:
        path: ~/rspec
        destination: build
    - store_test_results:
        path: ~/rspec
