version: 2.1

jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
    - image: circleci/ruby:2.4.2-jessie-node # the primary container, where your job's commands are run
    steps:
    - checkout # check out the code in the project directory
    - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
    - run: mkdir ~/rspec
    - run:
        command: touch ~/rspec/rspec.xml
    - run:
        command: bundle exec rspec --format documentation  --format RspecJunitFormatter -o ~/rspec/rspec.xml
        when: always
    - store_artifacts:
        path: ~/rspec
        destination: build
    - store_test_results:
        path: ~/rspec

  allure:
    docker:
    - image: automationwizards/allure:1.4.24.RC3
    steps:
    - checkout
    - run:
      command: "echo 'hola'"

workflows:
  version: 2
  workflow:
    jobs:
    - build
    - allure
